### ISSUE TITLE
日期数据

### ISSUE THREAD

**Issue by lixx3811** [chatopera/efaqa-corpus-zh#2]
请问time这个variable下时间的日期信息是没有办法获得的吗？

**Comment by Samurais** [comment]
因为数据来自不同数据源，time格式不统一，但是对于同一条记录，chats按照time
升序排列。

time虽然格式不统一，有的是完整的，有的是不完整的，不完整的代表包含年月日时分秒的部分信息。

你需要time完整日期信息的原因是什么？

**Comment by lixx3811** [comment]
谢谢您的回复，因为我是觉得不同日期段可能有一些热点问题会让造成社会性的焦虑，从而在这个数据上反映出来。

**Comment by Samurais** [comment]
推荐查看给力心理的近期问题，https://www.geilixinli.com/
