### ISSUE TITLE
请问下的lable分类里的s1，s2,s3怎么在数据集中没有啊

### ISSUE THREAD

**Issue by LZL1997** [chatopera/efaqa-corpus-zh#5]
{"chats": [{"time": "23:37:08", "value": "在这里想解决什么问题呢？", "sender": "audience", "type": "textMessage", "label": {"question": false, "knowledge": false, "negative": false}}, {"time": "23:38:22", "sender": "audience", "type": "textMessage", "value": "诶嘿嘿嘿", "label": {"question": false, "knowledge": false, "negative": false}}, {"time": "23:39:04", "sender": "owner", "type": "textMessage", "value": "吼吼", "label": {"s3": "", "attitude": ""}}, {"time": "23:46:04", "sender": "audience", "type": "textMessage", "value": "还在追海贼", "label": {"question": false, "knowledge": false, "negative": false}}, {"time": "23:47:14", "sender": "audience", "type": "textMessage", "value": "还在追JOJO……_§:з)))」∠)_", "label": {"question": false, "knowledge": false, "negative": false}}, {"time": "23:49:44", "sender": "owner", "type": "textMessage", "value": "推荐推荐", "label": {"s3": "", "attitude": ""}}, {"time": "23:51:33", "sender": "audience", "type": "textMessage", "value": "一休哥", "label": {"question": false, "knowledge": false, "negative": false}}], "owner": "匿名", "title": "女 ─=≡Σ((( つ•̀Ω•́)つ 有喜欢看动漫的吗？", "md5": "86cab1d9193139608772a2924c1f8b51"}

**Comment by Samurais** [comment]
使用 Github 最新数据

https://github.com/chatopera/efaqa-corpus-zh
