### ISSUE TITLE
示例数据和提供的数据怎么感觉对话不流畅，问题和回答很奇怪。

### ISSUE THREAD

**Issue by wotulong** [chatopera/efaqa-corpus-zh#6]
## 来自

- 公司：
- 产品：

# 描述

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
给出例子，感谢！
